name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 9 * * *" # Roda todo dia às 19:00 BRT (22:00 UTC)

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      MS_EMAIL: ${{ secrets.MS_EMAIL }}
      MS_SENHA: ${{ secrets.MS_SENHA }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencias
        run: npm ci

      - name: Install Playwright navegador
        run: npx playwright install chromium --with-deps

      - name: Rodando testes Playwright
        run: npx playwright test --reporter=html

      - name: Gerando Relatorio em PDF dos testes
        if: always()
        run: node generate-pdf.js

      - name: Enviar e-mail de relatório de teste com anexo em PDF
        uses: dawidd6/action-send-mail@v6
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_RELATORIO }}
          password: ${{ secrets.SENHA_RELATORIO }}
          to: ${{ secrets.REPORT_RECIPIENT }}
          from: GitHub Actions Test Report <${{ secrets.EMAIL_RELATORIO }}>
          subject: |
            ${{ job.status == 'success' && '✅ SUCESSO' || '🚨 FALHA' }} | Playwright Tests | Relatório PDF
          body: |
            Olá,

            Dev , os testes de Playwright foram concluídos.
            Status dos testes: ${{ job.status }}.

            O relatório completo está ANEXADO neste email como **report.pdf**.
            Para visualizar, abra o arquivo PDF em seu leitor de PDF preferido.

            Pipeline: ${{ github.workflow }}
            Branch: ${{ github.ref_name }}
            Commit SHA: ${{ github.sha }}

            Para ver o log completo do pipeline, clique no link abaixo:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: report.pdf
